### ISSUE TITLE
MacOS 11.6 failed to run

### ISSUE THREAD

**Issue by sentenes** [mallowigi/iconGenerator#63]
branch: master
```shell
❯ npm run example

> atom-icon-generator@1.0.0 example /Users/zhangyujia/Downloads/iconGenerator-master
> ts-node ./bin/examples --all

/Users/zhangyujia/Downloads/iconGenerator-master/bin/examples:27
#!/usr/bin/env node
^

SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at main (/Users/zhangyujia/Downloads/iconGenerator-master/node_modules/ts-node/src/bin.ts:198:14)
    at Object.<anonymous> (/Users/zhangyujia/Downloads/iconGenerator-master/node_modules/ts-node/src/bin.ts:288:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! atom-icon-generator@1.0.0 example: `ts-node ./bin/examples --all`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the atom-icon-generator@1.0.0 example script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zhangyujia/.npm/_logs/2021-09-28T09_44_22_092Z-debug.log
```

**Comment by mallowigi** [comment]
probably caused by the renovate updates, i'll take a look next time i'll update it

**Comment by sentenes** [comment]
Thanks!
log
```log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'wiki' ]
2 info using npm@6.14.13
3 info using node@v14.17.1
4 verbose run-script [ 'prewiki', 'wiki', 'postwiki' ]
5 info lifecycle atom-icon-generator@1.0.0~prewiki: atom-icon-generator@1.0.0
6 info lifecycle atom-icon-generator@1.0.0~wiki: atom-icon-generator@1.0.0
7 verbose lifecycle atom-icon-generator@1.0.0~wiki: unsafe-perm in lifecycle true
8 verbose lifecycle atom-icon-generator@1.0.0~wiki: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/zhangyujia/Downloads/iconGenerator/node_modules/.bin:/opt/maven3.6.3/bin:/usr/local/mysql/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_281.jdk/Contents/Home/bin:/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/go/bin
9 verbose lifecycle atom-icon-generator@1.0.0~wiki: CWD: /Users/zhangyujia/Downloads/iconGenerator
10 silly lifecycle atom-icon-generator@1.0.0~wiki: Args: [ '-c', 'ts-node ./bin/wiki all -o file' ]
11 silly lifecycle atom-icon-generator@1.0.0~wiki: Returned: code: 1  signal: null
12 info lifecycle atom-icon-generator@1.0.0~wiki: Failed to exec wiki script
13 verbose stack Error: atom-icon-generator@1.0.0 wiki: `ts-node ./bin/wiki all -o file`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:375:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:375:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid atom-icon-generator@1.0.0
15 verbose cwd /Users/zhangyujia/Downloads/iconGenerator
16 verbose Darwin 20.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "wiki"
18 verbose node v14.17.1
19 verbose npm  v6.14.13
20 error code ELIFECYCLE
21 error errno 1
22 error atom-icon-generator@1.0.0 wiki: `ts-node ./bin/wiki all -o file`
22 error Exit status 1
23 error Failed at the atom-icon-generator@1.0.0 wiki script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
